# Generated by Django 4.2.2 on 2023-07-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='AudioRecords',
        ),
    ]
